import {Tag, VoidElement} from './elementRep'
import {ChildTag, Child} from './nodeRep'
import {TagName} from '../decorator'

function t<E extends HTMLElement>(name: string) {
  return function(props: any, ...children: ChildTag[]) {
    return new Tag(name, props, children)
  }
}

function v<E extends HTMLElement>(name: string) {
  return function(props: any) {
    return new VoidElement(name, props)
  }
}

export var a              = t<HTMLAnchorElement>('c')
export var abbr           = t<HTMLPhraseElement>('abbr')
export var acronym        = t<HTMLPhraseElement>('acronym')
export var address        = t<HTMLBlockElement>('address')
export var applet         = t<HTMLAppletElement>('applet')
export var audio          = t<HTMLAudioElement>('audio')
export var b              = t<HTMLPhraseElement>('b')
export var basefont       = t<HTMLBaseFontElement>('basefont')
export var bdo            = t<HTMLPhraseElement>('bdo')
export var big            = t<HTMLPhraseElement>('big')
export var blockquote     = t<HTMLBlockElement>('blockquote')
export var body           = t<HTMLBodyElement>('body')
export var button         = t<HTMLButtonElement>('button')
export var canvas         = t<HTMLCanvasElement>('canvas')
export var caption        = t<HTMLTableCaptionElement>('caption')
export var center         = t<HTMLBlockElement>('center')
export var cite           = t<HTMLPhraseElement>('cite')
export var code           = t<HTMLPhraseElement>('code')
export var colgroup       = t<HTMLTableColElement>('colgroup')
export var datalist       = t<HTMLDataListElement>('datalist')
export var dd             = t<HTMLDDElement>('dd')
export var del            = t<HTMLModElement>('del')
export var dfn            = t<HTMLPhraseElement>('dfn')
export var dir            = t<HTMLDirectoryElement>('dir')
export var div            = t<HTMLDivElement>('div')
export var dl             = t<HTMLDListElement>('dl')
export var dt             = t<HTMLDTElement>('dt')
export var em             = t<HTMLPhraseElement>('em')
export var fieldset       = t<HTMLFieldSetElement>('fieldset')
export var font           = t<HTMLFontElement>('font')
export var form           = t<HTMLFormElement>('form')
export var frame          = t<HTMLFrameElement>('frame')
export var frameset       = t<HTMLFrameSetElement>('frameset')
export var h1             = t<HTMLHeadingElement>('h1')
export var h2             = t<HTMLHeadingElement>('h2')
export var h3             = t<HTMLHeadingElement>('h3')
export var h4             = t<HTMLHeadingElement>('h4')
export var h5             = t<HTMLHeadingElement>('h5')
export var h6             = t<HTMLHeadingElement>('h6')
export var head           = t<HTMLHeadElement>('head')
export var html           = t<HTMLHtmlElement>('html')
export var i              = t<HTMLPhraseElement>('i')
export var iframe         = t<HTMLIFrameElement>('iframe')
export var ins            = t<HTMLModElement>('ins')
export var isindex        = t<HTMLIsIndexElement>('isindex')
export var kbd            = t<HTMLPhraseElement>('kbd')
export var label          = t<HTMLLabelElement>('label')
export var legend         = t<HTMLLegendElement>('legend')
export var li             = t<HTMLLIElement>('li')
export var listing        = t<HTMLBlockElement>('listing')
export var map            = t<HTMLMapElement>('map')
export var marquee        = t<HTMLMarqueeElement>('marquee')
export var menu           = t<HTMLMenuElement>('menu')
export var nextid         = t<HTMLNextIdElement>('nextid')
export var nobr           = t<HTMLPhraseElement>('nobr')
export var object         = t<HTMLObjectElement>('object')
export var ol             = t<HTMLOListElement>('ol')
export var optgroup       = t<HTMLOptGroupElement>('optgroup')
export var option         = t<HTMLOptionElement>('option')
export var p              = t<HTMLParagraphElement>('p')
export var plaintext      = t<HTMLBlockElement>('plaintext')
export var pre            = t<HTMLPreElement>('pre')
export var progress       = t<HTMLProgressElement>('progress')
export var q              = t<HTMLQuoteElement>('q')
export var rt             = t<HTMLPhraseElement>('rt')
export var ruby           = t<HTMLPhraseElement>('ruby')
export var s              = t<HTMLPhraseElement>('s')
export var samp           = t<HTMLPhraseElement>('samp')
export var script         = t<HTMLScriptElement>('script')
export var select         = t<HTMLSelectElement>('select')
export var small          = t<HTMLPhraseElement>('small')
export var span           = t<HTMLSpanElement>('span')
export var strike         = t<HTMLPhraseElement>('strike')
export var strong         = t<HTMLPhraseElement>('strong')
export var style          = t<HTMLStyleElement>('style')
export var sub            = t<HTMLPhraseElement>('sub')
export var sup            = t<HTMLPhraseElement>('sup')
export var table          = t<HTMLTableElement>('table')
export var tbody          = t<HTMLTableSectionElement>('tbody')
export var td             = t<HTMLTableDataCellElement>('td')
export var textarea       = t<HTMLTextAreaElement>('textarea')
export var tfoot          = t<HTMLTableSectionElement>('tfoot')
export var th             = t<HTMLTableHeaderCellElement>('th')
export var thead          = t<HTMLTableSectionElement>('thead')
export var title          = t<HTMLTitleElement>('title')
export var tr             = t<HTMLTableRowElement>('tr')
export var tt             = t<HTMLPhraseElement>('tt')
export var u              = t<HTMLPhraseElement>('u')
export var ul             = t<HTMLUListElement>('ul')
export var video          = t<HTMLVideoElement>('video')
export var xmp            = t<HTMLBlockElement>('xmp')

// void element
export var area           = v<HTMLAreaElement>('area')
export var base           = v<HTMLBaseElement>('base')
export var br             = v<HTMLBRElement>('br')
export var col            = v<HTMLTableColElement>('col')
export var embed          = v<HTMLEmbedElement>('embed')
export var hr             = v<HTMLHRElement>('hr')
export var img            = v<HTMLImageElement>('img')
export var input          = v<HTMLInputElement>('input')
export var keygen         = v<HTMLBlockElement>('keygen')
export var link           = v<HTMLLinkElement>('link')
export var meta           = v<HTMLMetaElement>('meta')
export var param          = v<HTMLParamElement>('param')
export var source         = v<HTMLSourceElement>('source')
export var track          = v<HTMLTrackElement>('track')
